# filepath: /zhouhq10.github.io/.github/workflows/gh-pages.yml
name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch name if different

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public